2016-05-18 18:23:59.541 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-05-18 18:24:04.379 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 18:24:35.858 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 18:25:59.373 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-05-18 18:25:59.409 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Karibuex':start(normal, []) in application_master:init/4 line 134
2016-05-18 18:26:59.698 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-18 18:26:59.729 [error] <0.194.0> CRASH REPORT Process <0.194.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Karibuex':start(normal, []) in application_master:init/4 line 134
2016-05-18 18:27:25.436 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-18 18:27:25.468 [error] <0.194.0> CRASH REPORT Process <0.194.0> with 0 neighbours exited with reason: bad return value nil from 'Elixir.Karibuex':start(normal, []) in application_master:init/4 line 134
2016-05-18 18:28:27.190 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-18 18:28:27.222 [error] <0.194.0> CRASH REPORT Process <0.194.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Karibuex':start(normal, []) in application_master:init/4 line 134
2016-05-18 18:29:26.769 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-05-18 18:29:26.801 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Karibuex':start(normal, []) in application_master:init/4 line 134
2016-05-18 18:30:34.461 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-18 18:30:34.494 [error] <0.194.0> CRASH REPORT Process <0.194.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Karibuex':start(normal, []) in application_master:init/4 line 134
2016-05-18 18:32:07.652 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-05-18 18:33:19.728 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 18:34:05.285 [error] <0.146.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.151.0> exit with reason normal in context child_terminated
2016-05-18 18:36:34.940 [error] <0.150.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.155.0> exit with reason normal in context child_terminated
2016-05-18 18:40:25.654 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 18:40:35.649 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 18:41:24.728 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 18:41:43.544 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 22:52:07.232 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 22:52:41.849 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 22:53:43.236 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 22:54:04.401 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 22:54:17.555 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 22:55:03.586 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:07:53.043 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-05-18 23:10:44.792 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:11:33.073 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:13:45.607 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:13:58.656 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:29:26.966 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:30:00.863 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:30:32.789 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:31:51.948 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-18 23:33:42.442 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-19 00:06:40.393 [error] <0.140.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.145.0> exit with reason normal in context child_terminated
2016-05-19 00:06:40.486 [error] <0.12.0> Loading of /Users/yannakoun/Project/Visibleo/karibuex/_build/test/lib/espec/ebin/Elixir.Espec.beam failed: badfile
2016-05-19 00:06:40.486 [error] emulator beam/beam_load.c(1278): Error loading module 'Elixir.Espec':
  module name in object code is Elixir.ESpec


2016-05-19 00:06:57.470 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-19 00:07:17.668 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-19 00:07:31.112 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-19 00:07:45.374 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-19 00:07:58.628 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-19 00:10:21.850 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 20:09:10.632 [error] <0.739.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.744.0> exit with reason normal in context child_terminated
2016-05-21 21:14:26.825 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 21:55:25.871 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 21:57:50.285 [error] <0.146.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.151.0> exit with reason normal in context child_terminated
2016-05-21 22:11:16.565 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.150.0> exit with reason normal in context child_terminated
2016-05-21 22:15:12.946 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:15:42.372 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:16:42.832 [error] <0.183.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.188.0> exit with reason normal in context child_terminated
2016-05-21 22:17:50.295 [error] <0.183.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.188.0> exit with reason normal in context child_terminated
2016-05-21 22:17:50.533 [error] <0.251.0> Supervisor {<0.251.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Unit':start_link([5000]) at undefined exit with reason {'EXIT',{function_clause,[{ezmq,bind,[<0.252.0>,tcp,[5000],[]],[{file,"src/ezmq.erl"},{line,64}]},{'Elixir.Karibuex.Server.Unit',start_link,1,[{file,"lib/karibuex/server/unit.ex"},{line,5}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib..."},...]}]}} in context start_error
2016-05-21 22:19:24.748 [error] <0.183.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.188.0> exit with reason normal in context child_terminated
2016-05-21 22:19:25.028 [error] <0.251.0> Supervisor {<0.251.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Unit':start_link([5000]) at undefined exit with reason {'EXIT',{function_clause,[{ezmq,bind,[<0.252.0>,tcp,[5000],[]],[{file,"src/ezmq.erl"},{line,64}]},{'Elixir.Karibuex.Server.Unit',start_link,1,[{file,"lib/karibuex/server/unit.ex"},{line,5}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib..."},...]}]}} in context start_error
2016-05-21 22:20:27.431 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:25:58.642 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:31:48.172 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:32:27.967 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:32:41.935 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:33:38.018 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:33:52.579 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:34:11.801 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:34:23.267 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:34:38.751 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:34:47.135 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:35:14.912 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:35:28.715 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:39:55.263 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:40:16.262 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:40:56.629 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:41:10.769 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:43:59.584 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:45:01.196 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:45:24.222 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:45:24.570 [error] <0.202.0> gen_fsm <0.202.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:45:24.570 [error] <0.202.0> CRASH REPORT Process <0.202.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:45:24.570 [error] <0.177.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.202.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 22:45:49.810 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:45:50.148 [error] <0.202.0> gen_fsm <0.202.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:45:50.148 [error] <0.202.0> CRASH REPORT Process <0.202.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:45:50.148 [error] <0.177.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.202.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 22:46:19.210 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:46:19.565 [error] <0.215.0> gen_fsm <0.215.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:46:19.565 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:46:19.566 [error] <0.190.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.215.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 22:47:05.258 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:47:05.618 [error] <0.215.0> gen_fsm <0.215.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:47:05.618 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:47:05.618 [error] <0.190.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.215.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 22:51:31.303 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:51:31.644 [error] <0.215.0> gen_fsm <0.215.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:51:31.644 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:51:31.644 [error] <0.190.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.215.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 22:52:41.692 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:52:42.048 [error] <0.215.0> gen_fsm <0.215.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:52:42.048 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:52:42.048 [error] <0.190.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.215.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 22:53:27.427 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:54:52.841 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:54:53.148 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Unit':start_link(5000) at undefined exit with reason {'EXIT',{function_clause,[{ezmq,send,[<0.210.0>,{#Ref<0.0.1.219>,<<"Hello world">>}],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.Karibuex.Server.Unit',loop,1,[{file,"lib/karibuex/server/unit.ex"},{line,13}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,...}]}} in context start_error
2016-05-21 22:55:10.503 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:55:26.701 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:55:57.271 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:56:02.735 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 22:59:43.469 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 22:59:43.826 [error] <0.216.0> gen_fsm <0.216.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:59:43.827 [error] <0.216.0> CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 22:59:43.827 [error] <0.190.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.216.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 23:00:01.251 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 23:00:23.106 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 23:00:23.406 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Unit':start_link(5000) at undefined exit with reason {'EXIT',{function_clause,[{ezmq,send,[<0.210.0>,{#Ref<0.0.3.157>,<<"Hello world">>}],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.Karibuex.Server.Unit',loop,1,[{file,"lib/karibuex/server/unit.ex"},{line,13}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,...}]}} in context start_error
2016-05-21 23:01:38.089 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 23:02:06.831 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 23:02:45.455 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 23:02:45.860 [error] <0.216.0> gen_fsm <0.216.0> in state connected terminated with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 23:02:45.860 [error] <0.216.0> CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566
2016-05-21 23:02:45.861 [error] <0.190.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.216.0> exit with reason bad argument in call to ezmq_frame:encode({normal,0}) line 107 in ezmq_link:send_frames/2 line 566 in context child_terminated
2016-05-21 23:02:55.357 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-21 23:03:20.606 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 23:03:40.175 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 23:03:55.972 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-21 23:04:13.250 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 02:49:25.810 [error] <0.146.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.151.0> exit with reason normal in context child_terminated
2016-05-22 02:49:58.137 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 02:50:44.558 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 02:50:44.890 [error] <0.202.0> Supervisor {<0.202.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason nil in context start_error
2016-05-22 02:52:37.586 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 02:59:11.626 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 02:59:30.747 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 02:59:31.069 [error] <0.202.0> Supervisor {<0.202.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason nil in context start_error
2016-05-22 03:00:15.695 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 03:02:24.043 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 03:04:24.668 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:04:55.936 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:05:00.498 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:05:54.240 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:32:08.552 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:35:53.754 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:36:14.650 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:36:36.985 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:37:22.986 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:42:34.870 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:42:35.184 [error] <0.202.0> gen_fsm <0.202.0> in state setup terminated with reason: bad argument in call to erlang:start_timer(-1, <0.202.0>, inet) in inet:start_timer/1 line 1630
2016-05-22 03:42:35.184 [error] <0.202.0> CRASH REPORT Process <0.202.0> with 0 neighbours exited with reason: bad argument in call to erlang:start_timer(-1, <0.202.0>, inet) in inet:start_timer/1 line 1630
2016-05-22 03:42:35.185 [error] <0.177.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.202.0> exit with reason bad argument in call to erlang:start_timer(-1, <0.202.0>, inet) in inet:start_timer/1 line 1630 in context child_terminated
2016-05-22 03:42:56.145 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:42:56.478 [error] <0.202.0> gen_fsm <0.202.0> in state setup terminated with reason: bad argument in call to erlang:start_timer(-1, <0.202.0>, inet) in inet:start_timer/1 line 1630
2016-05-22 03:42:56.478 [error] <0.202.0> CRASH REPORT Process <0.202.0> with 0 neighbours exited with reason: bad argument in call to erlang:start_timer(-1, <0.202.0>, inet) in inet:start_timer/1 line 1630
2016-05-22 03:42:56.478 [error] <0.177.0> Supervisor ezmq_link_sup had child undefined started with {ezmq_link,start_link,undefined} at <0.202.0> exit with reason bad argument in call to erlang:start_timer(-1, <0.202.0>, inet) in inet:start_timer/1 line 1630 in context child_terminated
2016-05-22 03:43:36.992 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:47:09.629 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:47:44.923 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:48:47.081 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:51:28.875 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:51:47.215 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:51:57.905 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:52:41.881 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 03:54:18.535 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 03:54:23.776 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:54:51.635 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 03:55:32.656 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:56:07.265 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 03:56:39.265 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 04:27:18.131 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:27:18.413 [error] <0.210.0> CRASH REPORT Process <0.210.0> with 0 neighbours exited with reason: bad return value: <0.211.0> in gen_server:init_it/6 line 356
2016-05-22 04:27:18.414 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason {'EXIT',{{badmatch,{error,{bad_return_value,<0.211.0>}}},[{'Elixir.Karibuex.Server.Uow',start_link,1,[{file,"lib/karibuex/server/uow.ex"},{line,6}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2016-05-22 04:27:18.436 [error] <0.211.0> gen_server <0.211.0> terminated with reason: bad return value: <0.211.0>
2016-05-22 04:27:18.436 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: bad return value: <0.211.0> in gen_server:terminate/7 line 826
2016-05-22 04:27:30.006 [error] <0.126.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.131.0> exit with reason normal in context child_terminated
2016-05-22 04:27:30.278 [error] <0.197.0> CRASH REPORT Process <0.197.0> with 0 neighbours exited with reason: bad return value: <0.198.0> in gen_server:init_it/6 line 356
2016-05-22 04:27:30.279 [error] <0.196.0> Supervisor {<0.196.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason {'EXIT',{{badmatch,{error,{bad_return_value,<0.198.0>}}},[{'Elixir.Karibuex.Server.Uow',start_link,1,[{file,"lib/karibuex/server/uow.ex"},{line,6}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2016-05-22 04:27:30.313 [error] <0.198.0> gen_server <0.198.0> terminated with reason: bad return value: <0.198.0>
2016-05-22 04:27:30.313 [error] <0.198.0> CRASH REPORT Process <0.198.0> with 0 neighbours exited with reason: bad return value: <0.198.0> in gen_server:terminate/7 line 826
2016-05-22 04:30:38.105 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:30:38.378 [error] <0.210.0> CRASH REPORT Process <0.210.0> with 0 neighbours exited with reason: bad return value: <0.211.0> in gen_server:init_it/6 line 356
2016-05-22 04:30:38.378 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason bad return value: <0.211.0> in context start_error
2016-05-22 04:30:38.404 [error] <0.211.0> gen_server <0.211.0> terminated with reason: bad return value: <0.211.0>
2016-05-22 04:30:38.404 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: bad return value: <0.211.0> in gen_server:terminate/7 line 826
2016-05-22 04:31:52.502 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:31:52.843 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: bad return value: <0.211.0> in gen_server:init_it/6 line 356
2016-05-22 04:31:52.843 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason bad return value: <0.211.0> in context start_error
2016-05-22 04:31:52.879 [error] <0.211.0> gen_server <0.211.0> terminated with reason: bad return value: <0.211.0>
2016-05-22 04:31:52.879 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: bad return value: <0.211.0> in gen_server:terminate/7 line 826
2016-05-22 04:32:25.146 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:32:25.423 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: bad return value: [<0.211.0>] in gen_server:init_it/6 line 356
2016-05-22 04:32:25.423 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason bad return value: [<0.211.0>] in context start_error
2016-05-22 04:32:25.447 [error] <0.211.0> gen_server <0.211.0> terminated with reason: bad return value: [<0.211.0>]
2016-05-22 04:32:25.447 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: bad return value: [<0.211.0>] in gen_server:terminate/7 line 826
2016-05-22 04:33:47.059 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:35:46.159 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:35:46.509 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason ok in context start_error
2016-05-22 04:36:10.307 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:36:33.723 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:36:48.177 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:36:48.486 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:36:48.486 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:36:48.486 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at <0.210.0> exit with reason no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in context shutdown_error
2016-05-22 04:36:48.498 [error] <0.211.0> gen_server <0.211.0> terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:36:48.498 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:38:30.071 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:38:30.369 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: {bad_call,{recv,infinity}} in 'Elixir.Karibuex.Server.Uow':handle_call/3 line 420
2016-05-22 04:38:30.369 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:38:30.379 [error] <0.211.0> gen_server <0.211.0> terminated with reason: {bad_call,{recv,infinity}}
2016-05-22 04:38:30.379 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:38:30.379 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason {'EXIT',{{bad_call,{recv,infinity}},{gen_server,call,[<0.210.0>,{recv,infinity},infinity]}}} in context start_error
2016-05-22 04:39:18.577 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:39:18.868 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: {bad_call,{recv,infinity}} in 'Elixir.Karibuex.Server.Uow':handle_call/3 line 420
2016-05-22 04:39:18.868 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:39:18.878 [error] <0.211.0> gen_server <0.211.0> terminated with reason: {bad_call,{recv,infinity}}
2016-05-22 04:39:18.878 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:39:18.878 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason {'EXIT',{{bad_call,{recv,infinity}},{gen_server,call,[<0.210.0>,{recv,infinity},infinity]}}} in context start_error
2016-05-22 04:39:32.350 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:39:32.634 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: {bad_call,{recv,infinity}} in 'Elixir.Karibuex.Server.Uow':handle_call/3 line 420
2016-05-22 04:39:32.634 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:39:32.659 [error] <0.211.0> gen_server <0.211.0> terminated with reason: {bad_call,{recv,infinity}}
2016-05-22 04:39:32.659 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:39:32.659 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason {'EXIT',{{bad_call,{recv,infinity}},{gen_server,call,[<0.210.0>,{recv,infinity},infinity]}}} in context start_error
2016-05-22 04:39:49.104 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:39:49.465 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: {bad_call,{recv,infinity}} in 'Elixir.Karibuex.Server.Uow':handle_call/3 line 420
2016-05-22 04:39:49.465 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:39:49.476 [error] <0.211.0> gen_server <0.211.0> terminated with reason: {bad_call,{recv,infinity}}
2016-05-22 04:39:49.477 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: {bad_call,{recv,infinity}} in gen_server:terminate/7 line 826
2016-05-22 04:39:49.477 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at undefined exit with reason {'EXIT',{{bad_call,{recv,infinity}},{gen_server,call,[<0.210.0>,{recv,infinity},infinity]}}} in context start_error
2016-05-22 04:40:29.688 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:40:30.017 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:40:30.017 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:40:30.028 [error] <0.211.0> gen_server <0.211.0> terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:40:30.028 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:40:30.028 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at <0.210.0> exit with reason no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in context child_terminated
2016-05-22 04:41:29.348 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:41:29.678 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:41:29.678 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:41:29.685 [error] <0.211.0> gen_server <0.211.0> terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:41:29.685 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:41:29.686 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at <0.210.0> exit with reason no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in context child_terminated
2016-05-22 04:42:31.922 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:42:32.247 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:42:32.247 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:42:32.257 [error] <0.211.0> gen_server <0.211.0> terminated with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28
2016-05-22 04:42:32.257 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in gen_server:terminate/7 line 826
2016-05-22 04:42:32.257 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at <0.210.0> exit with reason no function clause matching 'Elixir.Karibuex.Server.Uow':handle_cast({loop}, <0.211.0>) line 28 in context child_terminated
2016-05-22 04:53:28.721 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
2016-05-22 04:53:29.017 [error] <0.210.0> gen_server 'Elixir.Karibuex.Server.Uow' terminated with reason: bad return value: {no_reply,<0.211.0>}
2016-05-22 04:53:29.017 [error] <0.210.0> CRASH REPORT Process 'Elixir.Karibuex.Server.Uow' with 0 neighbours exited with reason: bad return value: {no_reply,<0.211.0>} in gen_server:terminate/7 line 826
2016-05-22 04:53:29.041 [error] <0.211.0> gen_server <0.211.0> terminated with reason: bad return value: {no_reply,<0.211.0>}
2016-05-22 04:53:29.041 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: bad return value: {no_reply,<0.211.0>} in gen_server:terminate/7 line 826
2016-05-22 04:53:29.042 [error] <0.209.0> Supervisor {<0.209.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Uow':start_link(5000) at <0.210.0> exit with reason bad return value: {no_reply,<0.211.0>} in context child_terminated
2016-05-22 04:53:29.047 [error] <0.215.0> gen_server <0.215.0> terminated with reason: bad return value: {no_reply,<0.211.0>}
2016-05-22 04:53:29.047 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: bad return value: {no_reply,<0.211.0>} in gen_server:terminate/7 line 826
2016-05-22 04:56:32.674 [error] <0.139.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.144.0> exit with reason normal in context child_terminated
